import { useState } from 'react'
import { useAuthStore } from '../../store/auth.store'
import type { AuthSession } from '../../../shared/types'
import './Auth.css'

interface Props { onLogin: () => void }

type Mode = 'login' | 'register'

export default function LoginScreen({ onLogin }: Props) {
  const { setSession } = useAuthStore()
  const [mode, setMode] = useState<Mode>('login')
  const [form, setForm] = useState({ name: '', email: '', password: '' })
  const [showMfa, setShowMfa] = useState(false)
  const [mfaCode, setMfaCode] = useState('')
  const [error, setError] = useState('')
  const [success, setSuccess] = useState('')
  const [loading, setLoading] = useState(false)

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault()
    setLoading(true); setError(''); setSuccess('')
    try {
      const res = await window.actionshell.auth.login({
        email: form.email,
        password: form.password,
        mfaCode: showMfa ? mfaCode : undefined
      })
      if (res.success && res.data) {
        if ((res.data as any).mfaRequired) {
          setShowMfa(true)
          setLoading(false)
          return
        }
        setSession(res.data as AuthSession)
        onLogin()
      } else {
        setError(res.error || 'Login failed')
      }
    } catch { setError('Login failed') }
    finally { setLoading(false) }
  }

  const handleRegister = async (e: React.FormEvent) => {
    e.preventDefault()
    setLoading(true); setError(''); setSuccess('')
    try {
      const res = await window.actionshell.auth.register(form)
      if (res.success && res.data) {
        if ((res.data as any).pending) {
          setSuccess('Registration successful! Your account is pending admin approval. You will be able to login once an admin approves your account.')
          setMode('login')
        } else {
          // First user — auto-logged in as super admin
          setSession(res.data as AuthSession)
          onLogin()
        }
      } else {
        setError(res.error || 'Registration failed')
      }
    } catch { setError('Registration failed') }
    finally { setLoading(false) }
  }

  return (
    <div className="auth-screen">
      <div className="auth-bg-grid" />
      <div className="auth-card animate-scaleIn">
        <div className="auth-logo">
          <AppLogo />
          <h1>{showMfa ? 'Two-step verification' : mode === 'login' ? 'Welcome back' : 'Create Account'}</h1>
          <p>{showMfa ? 'Verify your identity to proceed' : mode === 'login' ? 'Sign in to your ActionShell account' : 'Register for a new ActionShell account'}</p>
        </div>

        {showMfa ? (
          <form onSubmit={handleLogin}>
            <div className="form-group">
              <label className="form-label">Authenticator Code</label>
              <input className="form-input" type="text" placeholder="6-digit code" maxLength={6}
                value={mfaCode} onChange={e => setMfaCode(e.target.value)} required autoFocus />
              <p style={{fontSize:'12px',color:'var(--color-text-500)',marginTop:'6px'}}>
                Enter the 6-digit security code generated by your authenticator app.
              </p>
            </div>
            {error && <p className="form-error" style={{textAlign:'center'}}>{error}</p>}
            <button className="btn btn-primary" type="submit" disabled={loading} style={{width:'100%',padding:'10px'}}>
              {loading ? <><span className="spinner"/>Verifying...</> : 'Verify'}
            </button>
            <button type="button" className="btn btn-ghost" onClick={() => { setShowMfa(false); setError(''); setMfaCode('') }} style={{width:'100%',marginTop:'8px'}}>
              Back to Login
            </button>
          </form>
        ) : mode === 'login' ? (
          <form onSubmit={handleLogin}>
            <div className="form-group">
              <label className="form-label">Email</label>
              <input className="form-input" type="email" placeholder="admin@company.com"
                value={form.email} onChange={e => setForm(f => ({...f, email: e.target.value}))} required autoFocus />
            </div>
            <div className="form-group">
              <label className="form-label">Password</label>
              <input className="form-input" type="password" placeholder="••••••••"
                value={form.password} onChange={e => setForm(f => ({...f, password: e.target.value}))} required />
            </div>
            {error && <p className="form-error" style={{textAlign:'center'}}>{error}</p>}
            {success && <p className="form-success" style={{textAlign:'center',color:'#A6E3A1',fontSize:'13px',marginBottom:'12px'}}>{success}</p>}
            <button className="btn btn-primary" type="submit" disabled={loading} style={{width:'100%',padding:'10px'}}>
              {loading ? <><span className="spinner"/>Signing in...</> : 'Sign In'}
            </button>
            <p style={{textAlign:'center',marginTop:'16px',fontSize:'13px',color:'var(--color-text-400)'}}>
              Don't have an account?{' '}
              <button type="button" onClick={() => { setMode('register'); setError(''); setSuccess('') }}
                style={{color:'#00D4FF',background:'none',border:'none',cursor:'pointer',fontSize:'13px',fontWeight:600,textDecoration:'underline'}}>
                Register
              </button>
            </p>
          </form>
        ) : (
          <form onSubmit={handleRegister}>
            <div className="form-group">
              <label className="form-label">Full Name</label>
              <input className="form-input" type="text" placeholder="John Doe"
                value={form.name} onChange={e => setForm(f => ({...f, name: e.target.value}))} required autoFocus />
            </div>
            <div className="form-group">
              <label className="form-label">Email</label>
              <input className="form-input" type="email" placeholder="you@company.com"
                value={form.email} onChange={e => setForm(f => ({...f, email: e.target.value}))} required />
            </div>
            <div className="form-group">
              <label className="form-label">Password</label>
              <input className="form-input" type="password" placeholder="Min 8 characters"
                value={form.password} onChange={e => setForm(f => ({...f, password: e.target.value}))} required minLength={8} />
            </div>
            {error && <p className="form-error" style={{textAlign:'center'}}>{error}</p>}
            <button className="btn btn-primary" type="submit" disabled={loading} style={{width:'100%',padding:'10px'}}>
              {loading ? <><span className="spinner"/>Creating account...</> : 'Register'}
            </button>
            <p style={{textAlign:'center',marginTop:'16px',fontSize:'13px',color:'var(--color-text-400)'}}>
              Already have an account?{' '}
              <button type="button" onClick={() => { setMode('login'); setError(''); setSuccess('') }}
                style={{color:'#00D4FF',background:'none',border:'none',cursor:'pointer',fontSize:'13px',fontWeight:600,textDecoration:'underline'}}>
                Sign In
              </button>
            </p>
          </form>
        )}

        <p className="auth-footer-note">ActionShell — Enterprise SSH & SFTP Manager</p>
      </div>
    </div>
  )
}

function AppLogo() {
  return (
    <div style={{display:'flex',alignItems:'center',justifyContent:'center',gap:'12px',marginBottom:'8px'}}>
      <svg width="36" height="36" viewBox="0 0 40 40" fill="none">
        <rect width="40" height="40" rx="10" fill="url(#g2)"/>
        <path d="M10 26l6-10 6 10M17 23h6" stroke="white" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/>
        <path d="M25 14l5 5-5 5" stroke="#00D4FF" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/>
        <defs><linearGradient id="g2" x1="0" y1="0" x2="40" y2="40"><stop stopColor="#1E2A44"/><stop offset="1" stopColor="#0A0E1A"/></linearGradient></defs>
      </svg>
      <span style={{fontSize:'22px',fontWeight:800,color:'var(--color-text-100)',letterSpacing:'-0.03em'}}>ActionShell</span>
    </div>
  )
}
